import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Image from "next/image";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Photoverse",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} overflow-scroll`}
      >
        <header className="bg-black">
          <Link href={"/"}>
            <Image
              width={100}
              height={100}
              src={"/photoverse-logo.png"}
              alt="logo"
              className="block mx-auto"
            />
          </Link>
        </header>
        <main>{children}</main>
      </body>
    </html>
  );
}
